window.open('https://code.jinhy.uk')
window.open('https://server.jinhy.uk')
window.open('https://github.com/jinhyeokfang/?tab=repositories')
window.open('https://discord.com/channels/@me')
window.open('https://music.youtube.com')
